apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: heimdall
  name: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heimdall
  template:
    metadata:
      labels:
        app: heimdall
    spec:
      containers:
      - env:
        - name: TZ
          value: "Europe/Berlin"
        - name: MIN_HEAP
          value: "1G"
        - name: MAX_HEAP
          value: "2G"
        - name: ADAPTER_KAFKA_BOOTSTRAP_SERVERS
          value: "my-kafka.default.svc.cluster.local:9092"
        - name: ADAPTER_KAFKA_SCHEMA_REGISTRY
          value: "http://mysr-schema-registry.default.svc.cluster.local:8081"
        - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
          value: "2"
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_PROFILES_ACTIVE
          value: "h2"
        image: 054263578675.dkr.ecr.eu-west-1.amazonaws.com/heimdall
        imagePullPolicy: IfNotPresent
        name: heimdall
        ports:
        - containerPort: 8080
          name: heimdall 
          protocol: TCP
        volumeMounts:
        - mountPath: "/data"
          name: heimdall
      volumes:
        - name: heimdall
          persistentVolumeClaim:
            claimName: heimdall
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: heimdall
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: gp2
  resources:
    requests:
      storage: 6Gi

